### ISSUE TITLE
Translation Not Working [camera_setup]

### ISSUE THREAD

**Issue by pet1330** [pet1330/FInCoR#16]
I've managed to find the board and order all of the points, irrelevant of view point. However, as I have the 3D points, not the 2d image points, I can't use solvePnP to calculate the rotation, but I've tried (with the help of Tom) to do this myself. I've managed to line up the roation, but for some reason the translation is completely off. The file can be found [here](https://github.com/pet1330/FInCoR/blob/dump/camera_setup/src/camera_removed.py)

@marc-hanheide any idea why this isn't working?

**Comment by marc-hanheide** [comment]
Can you point me to the lines where this is implemented. I can't seem to find it. You can just select line numbers in github and refer to them easily like this: https://github.com/pet1330/FInCoR/blob/dump/camera_setup/src/camera_removed.py#L21-L31 (see http://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github for details).

**Comment by pet1330** [comment]
[This](https://github.com/pet1330/FInCoR/blob/dump/camera_setup/src/camera_removed.py#L277) was my issues, I was taking the cross product and then checking if the [x,y,z] were negative values. What I should have been checking is just the z value. This now works
