### ISSUE TITLE
Create Circle Generator

### ISSUE THREAD

**Issue by pet1330** [pet1330/FInCoR#4]
Create a python script for generating unique circles to be used with the circle detection algorithm. 
- [x] Supply outer circle diameter
- [x] Supply the number of circles needed
- [x] Calculate circle separation based on range
- [x] Convert to PDF in order to keep sizes accurate when printing
- [x] Add left Margin
- [x] supply flag for creating calibration grid
- [x] Print ratio to the console

**Comment by marc-hanheide** [comment]
good idea indeed :-)
