### ISSUE TITLE
Store Previous calibration for quick restart

### ISSUE THREAD

**Issue by pet1330** [pet1330/FInCoR#5]
- [x] Generate / Overwrite the last calibration file in order to create yaml file with the relevant transforms
- [x] Pass argument to lookup transform, rather than calculate a new transform
- [x] Fallback to new calibration is file is not found

**Comment by pet1330** [comment]
Had a few issues dumping the rosparam data back into a yaml file, I'll get this sorted soon

**Comment by marc-hanheide** [comment]
You know how to do it now? Any help required?

**Comment by pet1330** [comment]
I think so, I just couldn't get it to work earlier, but I'll try and get it working again tomorrow morning.
