### ISSUE TITLE
Only viable circles are tracked

### ISSUE THREAD

**Issue by pet1330** [pet1330/FInCoR#6]
- [x] Extract pose from custom msg type
- [x] Use the 2D Bayes Tracker to give an estimation form a top down view
- [ ] Change the constant velocity model into a Brownian motion model
- [x] Adapt Bayes Tracker to work in 3D rather than 2D by providing a Z coordinate from pose msg

**Comment by marc-hanheide** [comment]
You want to integrate this with the [Bayesian tracker](https://github.com/strands-project/strands_perception_people/tree/indigo-devel/bayes_people_tracker] as @cdondrup suggest. It will give you 
- velocities for objects
- support for short-term occlusion
- more jitter-free positions

In fact, it would be a Kalman-like thing, so don't reinvent the wheel. Besides, I would not integrate any assumptions relating to the hand in the low level tracking, but in the higher level reasoning. E.g. you should model in your qualitative state that the hand was moved over an object and then the object was gone. But that should fall out of the high-level reasoning.

**Comment by pet1330** [comment]
I've updated the issue to reflect this
